### PR TITLE
Sung masterbranch

### PR DESCRIPTION
**Pull request by sunglim93**
Adding the QTE module to main

### CODE REVIEW

**Comment by IndentYourCode** [comment]
It might be a good idea to remove your main function from your QTE.py. In addition, maybe some more comments clearly stating what each QTE event looks like in more detail. Other than that it looks good!

**Comment by IndentYourCode** [comment]
OH! Also, we should set the WinFill to be none I think so it doesn't print over the rest of the screen.

**Comment by sunglim93** [comment]
> It might be a good idea to remove your main function from your QTE.py. In addition, maybe some more comments clearly stating what each QTE event looks like in more detail. Other than that it looks good!

The main shouldn't run because we'll only be calling functions from the imported library. I can comment them out to be doubly sure though!

**Comment by sunglim93** [comment]
> OH! Also, we should set the WinFill to be none I think so it doesn't print over the rest of the screen.

The only WIN.fill() left is in the comboQTE() which we will not be using until we figure out how we want to implement it with both keyboard and mouse input, so as long as we don't call it, we should be ok.

**Comment by IndentYourCode** [comment]
Sounds good. We can refactor them out later to make it a little cleaner.

**Review by IndentYourCode — APPROVED** [review]
Approved!

**Pull request merged**
